/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChatLieuDeGiay1;
import model.ChatLieuMatGiay1;
import model.ChiTietSanPham1;
import model.DanhMuc1;
import model.GiamGia1;
import model.MauSac1;
import model.SanPham1;
import model.Size1;
import repository.SanPhamRepository;
import repository.ThuocTinhRepository;

/**
 *
 * @author trung
 */
public class JFrameSanPham extends javax.swing.JFrame {

    private DefaultTableModel mol = new DefaultTableModel();
    private ThuocTinhRepository thuocTinhRepo = new ThuocTinhRepository();
    private SanPhamRepository sanPhamRepo = new SanPhamRepository();
    private int index = -1;

    /**
     * Creates new form JFrameSanPham
     */
    public JFrameSanPham() {
        initComponents();
        setLocationRelativeTo(null);
        for (SanPham1 sp : sanPhamRepo.getSanPham()) {
            cboSanPham.addItem(sp.getTenSP());
        }

        for (ChatLieuDeGiay1 cldg : thuocTinhRepo.getChatLieuDeGiay1()) {
            cboChatLieuDG.addItem(cldg.getTenChatLieuDe());
        }

        for (ChatLieuMatGiay1 clmg : thuocTinhRepo.getChatLieuMatGiay1()) {
            cboChatLieuMG.addItem(clmg.getTenChatLieu());
        }

        for (Size1 sz : thuocTinhRepo.getSize()) {
            cboSize.addItem(String.valueOf(sz.getKichThuoc()));
        }

        for (MauSac1 ms : thuocTinhRepo.getMauSac1()) {
            cboMauSac.addItem(ms.getTenMau());
        }

        for (GiamGia1 gg1 : thuocTinhRepo.getGiamGia()) {
            cboGiamGia.addItem(String.valueOf(gg1.getTenMaGiam()));
        }

        for (DanhMuc1 dm1 : thuocTinhRepo.getDanhMuc()) {
            cboDanhMuc.addItem(dm1.getTenDanhMuc());
        }
        this.fillSanPham(sanPhamRepo.getSanPham());
        this.fillCldg1(thuocTinhRepo.getChatLieuDeGiay1());
        this.fillCtsp(sanPhamRepo.getChiTietSanPham1());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jpnNavigation = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNgayCapNhat = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        rdoConHang = new javax.swing.JRadioButton();
        rdoHetHang = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMaCTSP = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboSanPham = new javax.swing.JComboBox<>();
        cboChatLieuMG = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cboChatLieuDG = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        cboGiamGia = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        btnLamMoiCTSP = new javax.swing.JButton();
        btnXoaCTSP = new javax.swing.JButton();
        btnSuaCTSP = new javax.swing.JButton();
        btnThemCTSP = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btnLamMoiThuocTinh = new javax.swing.JButton();
        btnXoaThuocTinh = new javax.swing.JButton();
        btnSuaThuocTinh = new javax.swing.JButton();
        btnThemThuocTinh = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        rdoSize = new javax.swing.JRadioButton();
        rdoDanhMuc = new javax.swing.JRadioButton();
        rdoMauSac = new javax.swing.JRadioButton();
        rdoChatLieuMat = new javax.swing.JRadioButton();
        rdoChatLieuDe = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        txtMaThuocTinh = new javax.swing.JTextField();
        txtTenThuocTinh = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rdoDangKinhDoanh = new javax.swing.JRadioButton();
        rdoNgungKinhDoanh = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThuocTinh = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnNavigation.setBackground(new java.awt.Color(153, 153, 255));
        jpnNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconSwing/Shop.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(204, 204, 255));
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(0, 0, 255));
        btnSanPham.setText("Quản lý sản phẩm");
        btnSanPham.setBorder(new javax.swing.border.MatteBorder(null));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 153));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnNavigationLayout = new javax.swing.GroupLayout(jpnNavigation);
        jpnNavigation.setLayout(jpnNavigationLayout);
        jpnNavigationLayout.setHorizontalGroup(
            jpnNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(45, 45, 45))
            .addGroup(jpnNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnNavigationLayout.setVerticalGroup(
            jpnNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNavigationLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(42, 42, 42))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel2)
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });
        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Ngày Nhập", "Ngày Cập Nhật", "Trạng Thái", "Danh Mục"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Mã Sản Phẩm");

        txtMaSP.setEditable(false);

        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setText("Trạng Thái");

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        txtNgayCapNhat.setEditable(false);

        txtNgayNhap.setEditable(false);

        jLabel5.setText("Ngày Nhập");

        jLabel6.setText("Ngày Cập Nhật");

        jLabel7.setText("Danh Mục");

        cboDanhMuc.setMinimumSize(new java.awt.Dimension(150, 26));
        cboDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhMucActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoConHang);
        rdoConHang.setSelected(true);
        rdoConHang.setText("Còn Hàng");
        rdoConHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoConHangActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoHetHang);
        rdoHetHang.setText("Hết Hàng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(550, 550, 550))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoConHang))
                                .addGap(18, 18, 18)
                                .addComponent(rdoHetHang)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoConHang)
                                    .addComponent(rdoHetHang)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setText("Làm Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Sản Phẩm", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel9.setText("Mã CTSP");

        txtMaCTSP.setEditable(false);

        txtSoLuong.setToolTipText("");
        txtSoLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("Số lượng");

        jLabel11.setText("Sản phẩm");

        jLabel12.setText("Đơn giá");

        cboSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSanPhamActionPerformed(evt);
            }
        });

        jLabel13.setText("Chất liệu mặt giày");

        jLabel14.setText("Chất liệu đế giày");

        jLabel15.setText("Size");

        jLabel16.setText("Màu sắc");

        jLabel17.setText("Mã giảm giá");

        jLabel19.setText("Mô tả");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboGiamGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtMaCTSP))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMauSac, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboSize, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboChatLieuDG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboChatLieuMG, 0, 147, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cboGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cboChatLieuMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboChatLieuDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnLamMoiCTSP.setText("Làm mới");
        btnLamMoiCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiCTSPActionPerformed(evt);
            }
        });

        btnXoaCTSP.setText("Xóa");
        btnXoaCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTSPActionPerformed(evt);
            }
        });

        btnSuaCTSP.setText("Sửa");
        btnSuaCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTSPActionPerformed(evt);
            }
        });

        btnThemCTSP.setText("Thêm");
        btnThemCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoiCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnThemCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoiCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CTSP", "Số lượng", "Đơn giá ", "Sản phẩm", "Chất liệu đế giày", "Size", "Màu sắc", "Chất liệu mặt giày", "Mô tả", "Mã giảm giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblCTSPMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tblCTSP);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Chi Tiết Sản Phẩm", jPanel6);

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnLamMoiThuocTinh.setText("Làm Mới");
        btnLamMoiThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiThuocTinhActionPerformed(evt);
            }
        });

        btnXoaThuocTinh.setText("Xóa");
        btnXoaThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuocTinhActionPerformed(evt);
            }
        });

        btnSuaThuocTinh.setText("Sửa");
        btnSuaThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThuocTinhActionPerformed(evt);
            }
        });

        btnThemThuocTinh.setText("Thêm");
        btnThemThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThemThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(btnSuaThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoiThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btnThemThuocTinh)
                .addGap(18, 18, 18)
                .addComponent(btnSuaThuocTinh)
                .addGap(18, 18, 18)
                .addComponent(btnXoaThuocTinh)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoiThuocTinh)
                .addGap(22, 22, 22))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thuộc Tính Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        buttonGroup1.add(rdoSize);
        rdoSize.setText("Size");
        rdoSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoSizeStateChanged(evt);
            }
        });
        rdoSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSizeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDanhMuc);
        rdoDanhMuc.setText("Danh mục");
        rdoDanhMuc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoDanhMucStateChanged(evt);
            }
        });
        rdoDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDanhMucActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMauSac);
        rdoMauSac.setText("Màu sắc");
        rdoMauSac.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoMauSacStateChanged(evt);
            }
        });
        rdoMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMauSacActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoChatLieuMat);
        rdoChatLieuMat.setText("Chất liệu mặt giày");
        rdoChatLieuMat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoChatLieuMatStateChanged(evt);
            }
        });
        rdoChatLieuMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChatLieuMatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoChatLieuDe);
        rdoChatLieuDe.setSelected(true);
        rdoChatLieuDe.setText("Chất liệu đế giày");
        rdoChatLieuDe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoChatLieuDeStateChanged(evt);
            }
        });
        rdoChatLieuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChatLieuDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rdoChatLieuDe)
                .addGap(39, 39, 39)
                .addComponent(rdoChatLieuMat)
                .addGap(42, 42, 42)
                .addComponent(rdoMauSac)
                .addGap(48, 48, 48)
                .addComponent(rdoDanhMuc)
                .addGap(31, 31, 31)
                .addComponent(rdoSize)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoChatLieuMat)
                    .addComponent(rdoMauSac)
                    .addComponent(rdoDanhMuc)
                    .addComponent(rdoSize)
                    .addComponent(rdoChatLieuDe))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Thuộc Tính", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtMaThuocTinh.setEditable(false);

        jLabel18.setText("Mã thuộc tính");

        jLabel20.setText("Tên thuộc tính");

        jLabel21.setText("Trạng thái");

        buttonGroup2.add(rdoDangKinhDoanh);
        rdoDangKinhDoanh.setSelected(true);
        rdoDangKinhDoanh.setText("Đang Kinh Doanh");

        buttonGroup2.add(rdoNgungKinhDoanh);
        rdoNgungKinhDoanh.setText("Ngừng Kinh Doanh");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(rdoDangKinhDoanh)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNgungKinhDoanh))
                            .addComponent(txtTenThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMaThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTenThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(rdoDangKinhDoanh)
                    .addComponent(rdoNgungKinhDoanh))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tblThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuộc tính", "Tên thuộc tính", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuocTinhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThuocTinh);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Thuộc Tính Sản Phẩm", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        setVisible(false);
        new JFrameSanPham().setVisible(true);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        setVisible(false);
        new JFrameMain().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        index = tblSanPham.getSelectedRow();
        this.showSanPham(index);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void cboDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDanhMucActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       if(checkSp()){
            if (sanPhamRepo.addSanPham(this.readSp()) > 0) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
        this.fillSanPham(sanPhamRepo.getSanPham());
       }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        index = tblSanPham.getSelectedRow();
        Integer ma = Integer.parseInt(tblSanPham.getValueAt(index, 0).toString());
        if(checkSp()){
            if (sanPhamRepo.updateSanPham(this.readSp2(), ma) > 0) {
            JOptionPane.showMessageDialog(this, "Sửa Thành công ");
            this.fillSanPham(sanPhamRepo.getSanPham());
        } else {
            JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
        }
        }


    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaSP.setText("");
        txtNgayNhap.setText("");
        txtNgayCapNhat.setText("");
        txtTenSP.setText("");
        rdoConHang.setSelected(true);
        cboDanhMuc.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void cboSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSanPhamActionPerformed

    private void btnLamMoiCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiCTSPActionPerformed
        txtMaCTSP.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        cboGiamGia.setSelectedIndex(0);
        txtMoTa.setText("");
        cboSanPham.setSelectedIndex(0);
        cboChatLieuDG.setSelectedIndex(0);
        cboChatLieuMG.setSelectedIndex(0);
        cboMauSac.setSelectedIndex(0);
        cboSize.setSelectedIndex(0);
    }//GEN-LAST:event_btnLamMoiCTSPActionPerformed

    private void btnXoaCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTSPActionPerformed

    }//GEN-LAST:event_btnXoaCTSPActionPerformed

    private void btnSuaCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTSPActionPerformed
        index = tblCTSP.getSelectedRow();
        Integer ma = Integer.parseInt(tblCTSP.getValueAt(index, 0).toString());
        if(checkSpct()){
            if (sanPhamRepo.updateSanPhamCT(this.readCtsp1(), ma) > 0) {
            JOptionPane.showMessageDialog(this, "Sửa Thành công ");
            this.fillCtsp(sanPhamRepo.getChiTietSanPham1());
        } else {
            JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
        }
        }
    }//GEN-LAST:event_btnSuaCTSPActionPerformed

    private void btnThemCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTSPActionPerformed
       if(checkSpct()){
        if (sanPhamRepo.addCtSanPham(this.readCtsp1()) > 0) {
            JOptionPane.showMessageDialog(this, "thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "thêm thất bại");
        }
        this.fillCtsp(sanPhamRepo.getChiTietSanPham1());
       }
    }//GEN-LAST:event_btnThemCTSPActionPerformed

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked
        index = tblCTSP.getSelectedRow();
        this.showChitietSp(index);
    }//GEN-LAST:event_tblCTSPMouseClicked

    private void tblCTSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_tblCTSPMouseEntered

    private void btnLamMoiThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiThuocTinhActionPerformed
        txtMaThuocTinh.setText("");
        txtTenThuocTinh.setText("");
        rdoDangKinhDoanh.setSelected(true);
    }//GEN-LAST:event_btnLamMoiThuocTinhActionPerformed

    private void btnXoaThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuocTinhActionPerformed

    }//GEN-LAST:event_btnXoaThuocTinhActionPerformed

    private void btnSuaThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThuocTinhActionPerformed
        index = tblThuocTinh.getSelectedRow();
        Integer ma = Integer.parseInt(tblThuocTinh.getValueAt(index, 0).toString());
        if(checkTT()){
            if (rdoChatLieuMat.isSelected()) {
            if (thuocTinhRepo.updateChatLieu(this.readClMatGiay1(), ma) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa Thành công ");
                this.fillClmg1(thuocTinhRepo.getChatLieuMatGiay1());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
            }

        } else if (rdoChatLieuDe.isSelected()) {
            if (thuocTinhRepo.updateChatLieuDe(this.readClDeGiay1(), ma) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa Thành công ");
                this.fillCldg1(thuocTinhRepo.getChatLieuDeGiay1());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
            }

        } else if (rdoDanhMuc.isSelected()) {
            if (thuocTinhRepo.updateDanhMuc(this.readDanhMuc1(), ma) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa Thành công ");
                this.fillDanhMuc(thuocTinhRepo.getDanhMuc());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
            }

        } else if (rdoMauSac.isSelected()) {
            if (thuocTinhRepo.UpdateMauSac(this.readMauSac1(), ma) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa Thành công ");
                this.fillMauSac(thuocTinhRepo.getMauSac1());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
            }

        } else if (rdoSize.isSelected()) {
            if (thuocTinhRepo.UpdateSize(this.readSize1(), ma) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa Thành công ");
                this.fillSize(thuocTinhRepo.getSize());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa Thất Bại");
            }

        }
        }

    }//GEN-LAST:event_btnSuaThuocTinhActionPerformed

    private void btnThemThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocTinhActionPerformed
        if(checkTT()){
            if (rdoChatLieuDe.isSelected()) {
            if (thuocTinhRepo.addChatLieuDe(this.readClDeGiay1()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
            }
            this.fillCldg1(thuocTinhRepo.getChatLieuDeGiay1());
        } else if (rdoChatLieuMat.isSelected()) {
            if (thuocTinhRepo.addChatLieuMat(this.readClMatGiay1()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
            }
            this.fillClmg1(thuocTinhRepo.getChatLieuMatGiay1());
        } else if (rdoDanhMuc.isSelected()) {
            if (thuocTinhRepo.addDanhMuc(this.readDanhMuc1()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
            }
            this.fillDanhMuc(thuocTinhRepo.getDanhMuc());
        } else if (rdoMauSac.isSelected()) {
            if (thuocTinhRepo.addMauSac(this.readMauSac1()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
            }
            this.fillMauSac(thuocTinhRepo.getMauSac1());
        } else if (rdoSize.isSelected()) {
            if (thuocTinhRepo.addSize(this.readSize1()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm Thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
            }
            this.fillSize(thuocTinhRepo.getSize());
        }
        }

    }//GEN-LAST:event_btnThemThuocTinhActionPerformed

    private void rdoSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoSizeStateChanged

    }//GEN-LAST:event_rdoSizeStateChanged

    private void rdoDanhMucStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoDanhMucStateChanged

    }//GEN-LAST:event_rdoDanhMucStateChanged

    private void rdoMauSacStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoMauSacStateChanged

    }//GEN-LAST:event_rdoMauSacStateChanged

    private void rdoChatLieuMatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoChatLieuMatStateChanged

    }//GEN-LAST:event_rdoChatLieuMatStateChanged

    private void rdoChatLieuDeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoChatLieuDeStateChanged

    }//GEN-LAST:event_rdoChatLieuDeStateChanged

    private void tblThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuocTinhMouseClicked
        index = tblThuocTinh.getSelectedRow();
        if (rdoChatLieuDe.isSelected()) {
            this.showCldg(index);
        } else if (rdoChatLieuMat.isSelected()) {
            this.showClmg(index);
        } else if (rdoDanhMuc.isSelected()) {
            this.showDanhMuc(index);
        } else if (rdoMauSac.isSelected()) {
            this.showMau(index);
        } else {
            this.showSize(index);
        }
    }//GEN-LAST:event_tblThuocTinhMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged

    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void rdoChatLieuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChatLieuDeActionPerformed
        // TODO add your handling code here:
        this.fillCldg1(thuocTinhRepo.getChatLieuDeGiay1());
    }//GEN-LAST:event_rdoChatLieuDeActionPerformed

    private void rdoChatLieuMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChatLieuMatActionPerformed
        // TODO add your handling code here:
        this.fillClmg1(thuocTinhRepo.getChatLieuMatGiay1());
    }//GEN-LAST:event_rdoChatLieuMatActionPerformed

    private void rdoMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMauSacActionPerformed
        // TODO add your handling code here:
        this.fillMauSac(thuocTinhRepo.getMauSac1());

    }//GEN-LAST:event_rdoMauSacActionPerformed

    private void rdoDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDanhMucActionPerformed
        // TODO add your handling code here:
        this.fillDanhMuc(thuocTinhRepo.getDanhMuc());
    }//GEN-LAST:event_rdoDanhMucActionPerformed

    private void rdoSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSizeActionPerformed
        // TODO add your handling code here:
        this.fillSize(thuocTinhRepo.getSize());
    }//GEN-LAST:event_rdoSizeActionPerformed

    private void rdoConHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoConHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoConHangActionPerformed

    //---------------------FIll-----------------------------------------------//
    private void fillSize(List<Size1> list) {
        mol = (DefaultTableModel) tblThuocTinh.getModel();
        mol.setRowCount(0);
        for (Size1 sz : list) {
            mol.addRow(sz.dataSize());
        }
    }

    private void fillDanhMuc(List<DanhMuc1> list) {
        mol = (DefaultTableModel) tblThuocTinh.getModel();
        mol.setRowCount(0);
        for (DanhMuc1 dm : list) {
            mol.addRow(dm.dataDanhMuc());
        }
    }

    private void fillCldg1(List<ChatLieuDeGiay1> list) {
        mol = (DefaultTableModel) tblThuocTinh.getModel();
        mol.setRowCount(0);
        for (ChatLieuDeGiay1 cldg1 : list) {
            mol.addRow(cldg1.dataCldg1());
        }
    }

    private void fillClmg1(List<ChatLieuMatGiay1> list) {
        mol = (DefaultTableModel) tblThuocTinh.getModel();
        mol.setRowCount(0);
        for (ChatLieuMatGiay1 clmg1 : list) {
            mol.addRow(clmg1.dataClmg1());
        }
    }

    private void fillMauSac(List<MauSac1> list) {
        mol = (DefaultTableModel) tblThuocTinh.getModel();
        mol.setRowCount(0);
        for (MauSac1 ms : list) {
            mol.addRow(ms.dataMauSac());
        }
    }

    private void fillSanPham(List<SanPham1> list) {
        mol = (DefaultTableModel) tblSanPham.getModel();
        mol.setRowCount(0);
        for (SanPham1 sp : list) {
            mol.addRow(sp.dataSanPham());
        }
    }

    private void fillCtsp(List<ChiTietSanPham1> list) {
        mol = (DefaultTableModel) tblCTSP.getModel();
        mol.setRowCount(0);
        for (ChiTietSanPham1 ctsp1 : list) {
            mol.addRow(ctsp1.dataSpChiTiet());
        }
    }

    //--------------------------------------------------------------------------
    //-----------------show-----------------------------------------------------
    private void showCldg(int index) {
        ChatLieuDeGiay1 cldg = thuocTinhRepo.getChatLieuDeGiay1().get(index);
        txtMaThuocTinh.setText(String.valueOf(cldg.getMaCLDe()));
        txtTenThuocTinh.setText(cldg.getTenChatLieuDe());
        if (cldg.isTrangThai()) {
            rdoDangKinhDoanh.setSelected(true);
        } else {
            rdoNgungKinhDoanh.setSelected(true);
        }
    }

    private void showClmg(int index) {
        ChatLieuMatGiay1 clmg = thuocTinhRepo.getChatLieuMatGiay1().get(index);
        txtMaThuocTinh.setText(String.valueOf(clmg.getMaCL()));
        txtTenThuocTinh.setText(clmg.getTenChatLieu());
        if (clmg.isTrangThai()) {
            rdoDangKinhDoanh.setSelected(true);
        } else {
            rdoNgungKinhDoanh.setSelected(true);
        }
    }

    private void showMau(int index) {
        MauSac1 ms = thuocTinhRepo.getMauSac1().get(index);
        txtMaThuocTinh.setText(String.valueOf(ms.getMaMS()));
        txtTenThuocTinh.setText(ms.getTenMau());
        if (ms.isTrangThai()) {
            rdoDangKinhDoanh.setSelected(true);
        } else {
            rdoNgungKinhDoanh.setSelected(true);
        }
    }

    private void showDanhMuc(int index) {
        DanhMuc1 dm = thuocTinhRepo.getDanhMuc().get(index);
        txtMaThuocTinh.setText(String.valueOf(dm.getMaDM()));
        txtTenThuocTinh.setText(dm.getTenDanhMuc());
        if (dm.isTrangThai()) {
            rdoDangKinhDoanh.setSelected(true);
        } else {
            rdoNgungKinhDoanh.setSelected(true);
        }
    }

    private void showSize(int index) {
        Size1 sz = thuocTinhRepo.getSize().get(index);
        txtMaThuocTinh.setText(String.valueOf(sz.getMaSize()));
        txtTenThuocTinh.setText(String.valueOf(sz.getKichThuoc()));
        if (sz.isTrangThai()) {
            rdoDangKinhDoanh.setSelected(true);
        } else {
            rdoNgungKinhDoanh.setSelected(true);
        }
    }

    private void showSanPham(int index) {
        SanPham1 sp1 = sanPhamRepo.getSanPham().get(index);
        txtMaSP.setText(String.valueOf(sp1.getMaSP()));
        txtTenSP.setText(sp1.getTenSP());
        txtNgayNhap.setText(String.valueOf(sp1.getNgayNhap()));
        txtNgayCapNhat.setText(String.valueOf(sp1.getNgayCapNhat()));
        if (sp1.isTrangThai()) {
            rdoConHang.setSelected(true);
        } else {
            rdoHetHang.setSelected(true);
        }
        cboDanhMuc.setSelectedItem(sp1.getMaDM());
    }

    private void showChitietSp(int index) {
        ChiTietSanPham1 ctsp = sanPhamRepo.getChiTietSanPham1().get(index);
        txtMaCTSP.setText(String.valueOf(ctsp.getMaCTSP()));
        txtSoLuong.setText(String.valueOf(ctsp.getSoLuong()));
        txtDonGia.setText(String.valueOf(ctsp.getDonGia()));
        txtMoTa.setText(ctsp.getMoTa());
        cboSanPham.setSelectedItem(ctsp.getMaSP().getTenSP());
        cboChatLieuMG.setSelectedItem(ctsp.getMaCL().getTenChatLieu());
        cboChatLieuDG.setSelectedItem(ctsp.getMaCLDe().getTenChatLieuDe());
        cboSize.setSelectedItem(String.valueOf(ctsp.getMaSize().getKichThuoc()));
        cboMauSac.setSelectedItem(ctsp.getMaMS().getTenMau());
        cboGiamGia.setSelectedItem(String.valueOf(ctsp.getMaGG().getMaGG()));
    }
//------------------------------------------------------------------------------
//-------------------------read-------------------------------------------------

    private ChatLieuDeGiay1 readClDeGiay1() {
        ChatLieuDeGiay1 cldg1 = new ChatLieuDeGiay1();
        cldg1.setTenChatLieuDe(txtTenThuocTinh.getText());
        if (rdoDangKinhDoanh.isSelected()) {
            cldg1.setTrangThai(true);
        } else {
            cldg1.setTrangThai(false);
        }
        return cldg1;
    }

    private ChatLieuMatGiay1 readClMatGiay1() {
        ChatLieuMatGiay1 clmg1 = new ChatLieuMatGiay1();
        clmg1.setTenChatLieu(txtTenThuocTinh.getText());
        if (rdoDangKinhDoanh.isSelected()) {
            clmg1.setTrangThai(true);
        } else {
            clmg1.setTrangThai(false);
        }
        return clmg1;
    }

    private MauSac1 readMauSac1() {
        MauSac1 ms = new MauSac1();
        ms.setTenMau(txtTenThuocTinh.getText());
        if (rdoDangKinhDoanh.isSelected()) {
            ms.setTrangThai(true);
        } else {
            ms.setTrangThai(false);
        }
        return ms;
    }

    private DanhMuc1 readDanhMuc1() {
        DanhMuc1 dm = new DanhMuc1();
        dm.setTenDanhMuc(txtTenThuocTinh.getText());
        if (rdoDangKinhDoanh.isSelected()) {
            dm.setTrangThai(true);
        } else {
            dm.setTrangThai(false);
        }
        return dm;
    }

    private Size1 readSize1() {
        Size1 sz = new Size1();
        sz.setKichThuoc(txtTenThuocTinh.getText());
        if (rdoDangKinhDoanh.isSelected()) {
            sz.setTrangThai(true);
        } else {
            sz.setTrangThai(false);
        }
        return sz;
    }

    private SanPham1 readSp() {
        SanPham1 sp1 = new SanPham1();
        sp1.setTenSP(txtTenSP.getText());
        sp1.setNgayNhap(LocalDate.now());
        sp1.setNgayCapNhat(LocalDate.now());
        if (rdoConHang.isSelected()) {
            sp1.setTrangThai(true);
        } else {
            sp1.setTrangThai(false);
        }
        for (DanhMuc1 dm1 : thuocTinhRepo.getDanhMuc()) {
            if (cboDanhMuc.getSelectedItem().equals(dm1.getTenDanhMuc())) {
                sp1.setMaDM(new DanhMuc1(dm1.getMaDM()));
            }
        }
        return sp1;
    }

    private SanPham1 readSp2() {
        SanPham1 sp1 = new SanPham1();
        sp1.setTenSP(txtTenSP.getText());
        sp1.setNgayCapNhat(LocalDate.now());
        if (rdoConHang.isSelected()) {
            sp1.setTrangThai(true);
        } else {
            sp1.setTrangThai(false);
        }
        for (DanhMuc1 dm1 : thuocTinhRepo.getDanhMuc()) {
            if (cboDanhMuc.getSelectedItem().equals(dm1.getTenDanhMuc())) {
                sp1.setMaDM(new DanhMuc1(dm1.getMaDM()));
            }
        }
        return sp1;
    }

    private ChiTietSanPham1 readCtsp1() {
        ChiTietSanPham1 ctsp1 = new ChiTietSanPham1();
        ctsp1.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        ctsp1.setDonGia(Float.parseFloat(txtDonGia.getText()));
        ctsp1.setMoTa(txtMoTa.getText());
        for (SanPham1 sp1 : sanPhamRepo.getSanPham()) {
            if (cboSanPham.getSelectedItem().equals(sp1.getTenSP())) {
                ctsp1.setMaSP(new SanPham1(sp1.getMaSP()));
            }
        }
        for (ChatLieuMatGiay1 clmg : thuocTinhRepo.getChatLieuMatGiay1()) {
            if (cboChatLieuMG.getSelectedItem().equals(clmg.getTenChatLieu())) {
                ctsp1.setMaCL(new ChatLieuMatGiay1(clmg.getMaCL()));
            }
        }
        for (ChatLieuDeGiay1 cldg : thuocTinhRepo.getChatLieuDeGiay1()) {
            if (cboChatLieuDG.getSelectedItem().equals(cldg.getTenChatLieuDe())) {
                ctsp1.setMaCLDe(new ChatLieuDeGiay1(cldg.getMaCLDe()));
            }
        }
        for (Size1 sz : thuocTinhRepo.getSize()) {
            if (cboSize.getSelectedItem().equals(sz.getKichThuoc())) {
                ctsp1.setMaSize(new Size1(sz.getMaSize()));
            }
        }
        for (MauSac1 ms : thuocTinhRepo.getMauSac1()) {
            if (cboMauSac.getSelectedItem().equals(ms.getTenMau())) {
                ctsp1.setMaMS(new MauSac1(ms.getMaMS()));
            }
        }
        for (GiamGia1 gg1 : thuocTinhRepo.getGiamGia()) {
            if (cboGiamGia.getSelectedItem().equals(gg1.getTenMaGiam())) {
                ctsp1.setMaGG(new GiamGia1(gg1.getMaGG()));
            }
        }
        return ctsp1;
    }

    //------------------------------check-------------------------------------//
    private Boolean checkTT() {
        if (txtTenThuocTinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên thuộc tính");
            return false;
        }
        if (rdoSize.isSelected()) {
        // Kiểm tra tên thuộc tính có phải là số không
        try {
            Double.parseDouble(txtTenThuocTinh.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tên thuộc tính phải là số khi bảng được chọn là 'size'");
            return false;
        }
    } else {
        // Kiểm tra tên thuộc tính có phải là chữ không
        if (!txtTenThuocTinh.getText().matches("[\\p{L}\\s]+")) {
            JOptionPane.showMessageDialog(this, "Tên thuộc tính phải là chữ");
            return false;
        }
    }
        return true;
    }
    
    private Boolean checkSp(){
        if (txtTenSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên Sản Phẩm");
            return false;
        }
        if (!txtTenSP.getText().matches("[\\p{L}\\s]+")) {
            JOptionPane.showMessageDialog(this, "Tên Sản Phẩm phải là chữ");
            return false;
        }
        return true;
    }

    private Boolean checkSpct(){
        try {
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên lớn hơn 0");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên hợp lệ");
            return false;
        }
         try {
            double Gia = Double.parseDouble(txtDonGia.getText());
            if (Gia <= 0) {
                JOptionPane.showMessageDialog(this, "Đơn giá phải là số lớn hơn 0");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là số thực hợp lệ");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLamMoiCTSP;
    private javax.swing.JButton btnLamMoiThuocTinh;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaCTSP;
    private javax.swing.JButton btnSuaThuocTinh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemCTSP;
    private javax.swing.JButton btnThemThuocTinh;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaCTSP;
    private javax.swing.JButton btnXoaThuocTinh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboChatLieuDG;
    private javax.swing.JComboBox<String> cboChatLieuMG;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboGiamGia;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboSanPham;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jpnNavigation;
    private javax.swing.JRadioButton rdoChatLieuDe;
    private javax.swing.JRadioButton rdoChatLieuMat;
    private javax.swing.JRadioButton rdoConHang;
    private javax.swing.JRadioButton rdoDangKinhDoanh;
    private javax.swing.JRadioButton rdoDanhMuc;
    private javax.swing.JRadioButton rdoHetHang;
    private javax.swing.JRadioButton rdoMauSac;
    private javax.swing.JRadioButton rdoNgungKinhDoanh;
    private javax.swing.JRadioButton rdoSize;
    private javax.swing.JTable tblCTSP;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTable tblThuocTinh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaCTSP;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMaThuocTinh;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNgayCapNhat;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenThuocTinh;
    // End of variables declaration//GEN-END:variables
}
